The algorithm dedpends on the Tensor Toolbox 2.4 or above, which is available at
   http://www.sandia.gov/~tgkolda/TensorToolbox/index-2.5.html

Matlab source code will be available after the paper is accepted.

Last updated: 2013-09-13

by Guoxu Zhou
E-mail: zhouguoxu@gmail.com
www.bsp.brain.riken.jp/~zhougx

Please feel free to contact if there are any problems and bugs.



NEITHER THE AUTHORS NOR THEIR EMPLOYERS ACCEPT ANY RESPONSIBILITY OR LIABILITY
FOR LOSS OR DAMAGE OCCASIONED TO ANY PERSON OR PROPERTY THROUGH USING SOFTWARE,
MATERIALS, INSTRUCTIONS, METHODS OR IDEAS CONTAINED HEREIN, OR ACTING OR REFRAINING
FROM ACTING AS A RESULT OF SUCH USE. THE AUTHORS EXPRESSLY DISCLAIM ALL IMPLIED 
WARRANTIES, INCLUDING MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE. 
THERE WILL BE NO DUTY ON THE AUTHORS TO CORRECT ANY ERRORS OR DEFECTS IN THE 
SOFTWARE. THIS SOFTWARE AND THE DOCUMENTATIONS ARE THE PROPERTY OF THE AUTHORS 
AND SHOULD ONLY BE USED FOR SCIENTIFIC AND EDUCATIONAL PURPOSES. ALL SOFTWARE 
IS PROVIDED FREE AND IT IS NOT SUPPORTED. THE AUTHORS ARE, HOWEVER, HAPPY TO 
RECEIVE COMMENTS, CRITICISM AND SUGGESTIONS ADDRESSED TO ZHOUGUOXU@GMAIL.COM