function algs = get_algs

% algs = { 'HORPCA-ADAL', 'HORPCA-TC-ADAL', 'RPCA', 'HORPCA-MIX-ADAL', ...
%         'HORPCA-MIX-TC-ADAL', 'HORPCA-TRMALM', 'HORPCA-MIX-FISTA', ...
%         'HORPCA-FISTA', 'HORPCA-TC-ADAL-ADP', 'RPCA-CS' };
    
algs = { 'HORPCA-S', 'HORPCA-S', 'RPCA', 'HORPCA-M', ...
        'HORPCA-M', 'TR-MALM', 'HORPCA-MP', ...
        'HORPCA-SP', 'HORPCA-S-ADP', 'HORPCA-S-NCX', 'HORPCA-S-NCX', ...
        'TUCKER-ADAL' };

end